FROM debian:buster

ARG ftp_user \
    ftp_pwd

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y vsftpd

RUN service vsftpd start

COPY  ./tools/script.sh /tmp/script.sh

RUN chmod +x /tmp/script.sh

ENTRYPOINT [ "/tmp/script.sh" ]

RUN service vsftpd stop

CMD ["/usr/sbin/vsftpd"]
