FROM debian:buster

RUN apt-get update -y && apt-get install -y nginx && apt-get install -y openssl && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/aouhadou.key -out /etc/ssl/certs/aouhadou.crt -subj="/C=MA/ST=BM/O=1337/CN=aouhadou.42.fr"

COPY ./conf/default /etc/nginx/sites-available/default

CMD ["nginx", "-g", "daemon off;" ]
